import { Check, ChevronRight, Circle, Clock3, LockKeyhole } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Card } from '@/components/ui/card'
import { Progress } from '@/components/ui/progress'
import { classModules } from '@/data/mockData'
import { AppShell } from '@/layouts/AppShell'
import { cn } from '@/lib/utils'
import type { LessonStatus } from '@/types'

const statusIcon: Record<LessonStatus, typeof Check> = { completed: Check, current: Circle, locked: LockKeyhole, upcoming: Clock3 }

export function StudentClassPage() {
  return <AppShell role="student" title="My Classes / Data Analytics"><div className="animate-enter rounded-xl border bg-card p-5 sm:p-7"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><Badge className="mb-4 border-primary/20 bg-accent text-accent-foreground">Active class</Badge><h1 className="text-2xl font-semibold tracking-[-0.035em] sm:text-3xl">Data Analytics — Batch 01</h1><p className="mt-2 text-sm text-muted-foreground">Build practical skills across the modern analytics toolkit.</p></div><div className="w-full lg:max-w-sm"><div className="mb-2 flex justify-between text-xs"><span className="text-muted-foreground">Course progress</span><span className="font-semibold">24%</span></div><Progress value={24} className="h-2" /></div></div></div><div className="animate-enter-delay mt-8 space-y-4">{classModules.map((module) => <Card key={module.name} className="overflow-hidden"><div className="flex flex-col gap-4 border-b bg-muted/20 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="font-semibold tracking-[-0.015em]">{module.name}</h2>{module.upcoming && <Badge>Upcoming</Badge>}</div><p className="mt-1 text-sm text-muted-foreground">{module.description}</p></div>{!module.upcoming && <span className="text-xs font-semibold">{module.progress}% complete</span>}</div>{module.lessons.length > 0 ? <div className="divide-y">{module.lessons.map((lesson) => { const Icon = statusIcon[lesson.status]; return <div key={lesson.id} className={cn('flex items-center justify-between gap-4 p-4 transition-colors sm:px-5', lesson.status === 'current' && 'bg-accent/55', lesson.status === 'locked' && 'opacity-60')}><div className="flex min-w-0 items-center gap-3"><span className={cn('flex size-8 shrink-0 items-center justify-center rounded-full border text-muted-foreground', lesson.status === 'completed' && 'border-primary bg-primary text-primary-foreground', lesson.status === 'current' && 'border-primary text-primary')}><Icon className={cn('size-3.5', lesson.status === 'current' && 'fill-primary')} /></span><div><p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-muted-foreground">{lesson.number}</p><p className="mt-0.5 text-sm font-medium">{lesson.title}</p></div></div><div className="flex items-center gap-2"><span className="hidden text-xs capitalize text-muted-foreground sm:inline">{lesson.status}</span>{lesson.status === 'current' && <ChevronRight className="size-4 text-primary" />}</div></div>})}</div> : <div className="flex items-center gap-3 p-5 text-sm text-muted-foreground"><Clock3 className="size-4" />Lessons will open as you progress through the course.</div>}</Card>)}</div></AppShell>
}
